version: '3'

services:
  # MySQL database service
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: superdupervpn
      MYSQL_USER: django
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: mysqladmin ping --silent
  # Django app service
  django:
    build:
      context: .
      dockerfile: docker/django/dockerfile
    ports:
      - "8000:8000"
    volumes:
      - my_shared_volume:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
    healthcheck:
      test: curl 127.0.0.1:8000

  #redis
  redis:
    image: redis:7.2.0-bookworm
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
  
  celery:
    build:
      context: .
      dockerfile: docker/celery/dockerfile
    volumes:
      - my_shared_volume:/app
      - /tmp:/wireguardconfig #where config for wireguard is on host machine
    depends_on:
      - redis
      - django
  
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/dockerfile
    ports:
      - "80:80"
    depends_on:
      - django



volumes:
  my_shared_volume: